In [1]:
import pandas as pd

# Dataset for human olfaction

## Dravnieks [c]

In [3]:
task_file = './fig1/c_Dravnieks/data.csv'
df = pd.read_csv(task_file)
df.head()

,smiles,regression_citrus,regression_lemon,regression_grapefruit,regression_orange,regression_fruity,regression_pineapple,regression_grape,regression_strawberry,regression_apple,...,regression_putrid,regression_fecal,regression_cadaverous,regression_sickening,regression_powdery,regression_chalky,regression_light,regression_heavy,regression_cooling,regression_warm
0,O=Cc1ccccc1,0.0504,0.0360,0.0072,0.0144,0.2230,0.0216,0.0072,0.0576,0.0000,...,0.0072,0.0000,0.0000,0.0504,0.0504,0.0072,0.2086,0.2734,0.1367,0.2158
1,CCCC(=O)O,0.0000,0.0071,0.0000,0.0000,0.0071,0.0000,0.0000,0.0000,0.0000,...,0.4786,0.3500,0.1357,0.6571,0.0143,0.0000,0.0286,0.3857,0.0000,0.1143
2,O=c1ccc2ccccc2o1,0.0286,0.0357,0.0000,0.0000,0.1429,0.0357,0.0071,0.0286,0.0143,...,0.0357,0.0000,0.0000,0.0714,0.0786,0.0143,0.2429,0.1357,0.1214,0.2071
3,CC(C)c1ccc(C=O)cc1,0.1071,0.1643,0.0214,0.0500,0.0714,0.0143,0.0000,0.0214,0.0000,...,0.0643,0.0000,0.0071,0.2000,0.1214,0.0214,0.1643,0.2429,0.1429,0.1786
4,Cc1cccc(O)c1,0.0000,0.0000,0.0000,0.0000,0.0216,0.0072,0.0000,0.0000,0.0000,...,0.0288,0.0432,0.0216,0.1439,0.1295,0.0000,0.1223,0.2446,0.0719,0.1439

## DREAM Olfaction Prediction Challenge (Keller et al.) [h]

In [5]:
task_file = './fig1/h_Keller_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

,smiles,regression_Intensity,regression_Pleasantness,regression_Bakery,regression_Sweet,regression_Fruit,regression_Fish,regression_Garlic,regression_Spices,regression_Cold,...,regression_Acid,regression_Warm,regression_Musky,regression_Sweaty,regression_Ammonia,regression_Decayed,regression_Wood,regression_Grass,regression_Flower,regression_Chemical
0,O=Cc1ccc(O)cc1,24.653061,48.956522,0.630435,24.347826,6.239130,0.282609,1.608696,3.652174,4.000000,...,2.847826,0.913043,8.304348,1.500000,1.804348,4.978261,1.260870,1.347826,9.260870,14.239130
1,CC=O,33.265306,45.315789,8.421053,20.078947,1.763158,0.000000,0.631579,2.500000,7.000000,...,4.447368,4.526316,3.421053,1.947368,3.789474,3.263158,1.026316,4.000000,2.184211,18.789474
2,CC(C)=O,16.714286,55.437500,3.375000,15.531250,6.468750,2.281250,2.593750,4.375000,7.625000,...,3.218750,10.031250,7.531250,0.031250,5.281250,6.218750,8.625000,6.593750,12.625000,10.500000
3,O=C(O)CCCCC(=O)O,6.877551,53.218750,1.750000,18.312500,1.312500,0.000000,1.906250,6.156250,5.562500,...,3.218750,9.437500,6.781250,6.093750,2.781250,6.906250,1.187500,2.218750,9.625000,7.750000
4,NCCC(=O)O,21.163265,51.351351,0.675676,8.567568,2.351351,1.000000,2.351351,2.729730,7.189189,...,3.891892,3.918919,5.243243,0.540541,0.189189,3.324324,4.891892,6.864865,5.783784,10.486486

## Human olfactory receptors (Gupta et al.) [j]

In [7]:
receptor_files = [
    './fig1/j_Gupta_et_al/OR1A1.csv',
    './fig1/j_Gupta_et_al/OR1A2.csv',
    './fig1/j_Gupta_et_al/OR1G1.csv',
    './fig1/j_Gupta_et_al/OR2J2.csv',
    './fig1/j_Gupta_et_al/OR2W1.csv',
    './fig1/j_Gupta_et_al/OR51E1.csv',
    './fig1/j_Gupta_et_al/OR51E2.csv', 
    './fig1/j_Gupta_et_al/OR52D1.csv',
]
receptor_idx = 0
df = pd.read_csv(receptor_files[receptor_idx])
df.head()

                          smiles  binary_classification_response
0       CC[C@@H](C(=O)O)c1ccccc1                               0
1     C=C1CC[C@H]2C[C@@H]1C2(C)C                               0
2  CC1(C)[C@H]2CC[C@]1(C)C(=O)C2                               0
3          C=C(C)C1CC=C(C)C(O)C1                               1
4  CC1(C)C(=O)[C@]2(C)CC[C@H]1C2                               0

# Dataset for mouse piriform cortex activity [f]

In [9]:
dataset_files = [
    './fig1/f_Pashkovski_et_al/clustered_pcx_l2.csv',
    './fig1/f_Pashkovski_et_al/clustered_pcx_l3.csv', 
    './fig1/f_Pashkovski_et_al/local_boutons.csv',
    './fig1/f_Pashkovski_et_al/local_pcx_l2.csv',
    './fig1/f_Pashkovski_et_al/local_pcx_l3.csv',
]
dataset_idx = 1
df = pd.read_csv(dataset_files[dataset_idx])
df.head() # neuron recoridng values for each dataset

,smiles,neuron_0,neuron_1,neuron_2,neuron_3,neuron_4,neuron_5,neuron_6,neuron_7,neuron_8,...,neuron_478,neuron_479,neuron_480,neuron_481,neuron_482,neuron_483,neuron_484,neuron_485,neuron_486,neuron_487
0,C[C@H](CCC=C(C)C)CC(=O)O,0.3,0.6,0.7,0.4,0.4,0.7,0.2,0.8,0.4,...,0.0,0.6,0.2,0.2,0.3,0.8,0.9,0.3,0.1,0.3
1,CCCCC(CC)C(=O)O,0.4,0.2,0.1,0.4,0.8,0.4,0.4,0.7,0.4,...,0.0,0.5,0.2,0.8,0.6,0.4,1.0,0.8,0.0,0.7
2,CCCCC(C)CCC(=O)O,0.4,0.4,0.7,0.6,0.7,0.3,0.7,0.9,0.3,...,0.2,1.0,0.2,0.3,0.3,0.8,0.8,0.8,0.0,0.6
3,CCCCCC(C)C(=O)O,0.7,0.5,0.5,0.3,0.6,0.9,0.1,1.0,0.4,...,0.1,1.0,0.1,0.6,0.4,0.6,0.7,0.7,0.0,0.7
4,CC(C)C(=O)OCCCC1=CC=CC=C1,0.4,0.2,0.2,0.8,0.3,0.5,0.4,0.6,0.6,...,0.4,0.3,0.3,1.0,0.7,0.7,0.9,0.4,0.1,1.0

# Dataset for insect olfaction

## MacWilliam et al. [a]

In [11]:
task_file = './fig1/a_MacWilliam_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

           smiles  binary_classification_preference_idx
0          CN(C)C                                     1
1  CCOC(=O)C(C)=O                                     0
2      CCC/C=C\CO                                     0
3         NCCCCCN                                     1
4      CC/C=C\CCO                                     0

## Xu et al. [b]

In [13]:
task_file = './fig1/b_Xu_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

               smiles  binary_classification_current_label
0  C=CC(CCCCC)OC(C)=O                                    1
1        C/C=C(\C)C=O                                    0
2               CCCCO                                    0
3              CCCCCO                                    0
4             CCCCCCO                                    1

## Wei et al. [d]

In [15]:
task_file = './fig1/d_Wei_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

                       smiles  binary_classification_above90@0.01
0    CCOC(=O)C1OC1(C)c1ccccc1                                   1
1           CCOc1cc(C=O)ccc1O                                   1
2           CCCCCCC1CCC(=O)O1                                   1
3   CC(=O)C=CC1=C(C)CCCC1(C)C                                   0
4  CC(C=O)Cc1ccc(C(C)(C)C)cc1                                   1

## Missbach et al. [e]

In [17]:
species_files = ['./fig1/e_Missbach_et_al/drosophila_melanogaster.csv',
                 './fig1/e_Missbach_et_al/lepismachilis_y-signata.csv',
                 './fig1/e_Missbach_et_al/phyllium_siccifolium.csv',
                 './fig1/e_Missbach_et_al/thermobia_domestica.csv',
                ]
species_idx = 0
df = pd.read_csv(species_files[species_idx])
df.head() # different tasks/neuron for each the first specie

879

## del Mármol et al. [g]

In [19]:
task_file = './fig1/g_del_Mármol_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

          smiles  regression_OR1  regression_OR5
0        CCCCCCO           1.262           4.202
1      CCCCCCCCO           8.261           4.661
2   C=CC(O)CCCCC           0.500           4.692
3         CCCCCO           0.366           1.434
4  CC(=O)c1cccs1           5.139           4.545

## Carey et al. [i]

In [21]:
task_file = './fig1/i_Carey_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

,smiles,regression_AgOr1,regression_AgOr2,regression_AgOr3,regression_AgOr4,regression_AgOr5,regression_AgOr6,regression_AgOr8,regression_AgOr9,regression_AgOr10,...,regression_AgOr59,regression_AgOr61,regression_AgOr63,regression_AgOr64,regression_AgOr65,regression_AgOr66,regression_AgOr67,regression_AgOr73,regression_AgOr75,regression_AgOr76
0,CC(=C)[C@@H]1CC=C(C)C(=O)C1,-5.000000,-2.400000,-2.000000,11.200000,2.333333,-3.000000,-3.600000,2.333333,2.333333,...,1.200000,1.666667,4.333333,5.333333,4.333333,-1.333333,-3.000000,-3.333333,33.666667,2.333333
1,CC1(C)[C@H]2CC[C@](C)(C2)C1=O,-12.333333,12.333333,-3.200000,14.400000,-6.333333,1.000000,-4.000000,1.333333,-0.333333,...,-1.000000,2.666667,25.333333,34.333333,-3.333333,13.666667,0.000000,-5.333333,27.600000,-5.333333
2,CC(=C)[C@H]1CC=C(C)C(=O)C1,-2.000000,-0.666667,6.333333,-0.333333,2.333333,3.200000,-1.333333,3.333333,6.333333,...,5.333333,3.600000,9.000000,6.000000,1.666667,-2.333333,-2.400000,-5.666667,36.000000,-5.333333
3,CC1(C)[C@@H]2CC[C@@](C)(C2)C1=O,-5.666667,1.000000,-1.666667,18.666667,-6.333333,-0.333333,-7.333333,1.666667,0.000000,...,-0.333333,3.333333,22.333333,51.000000,0.000000,14.000000,1.200000,-0.666667,20.333333,-7.666667
4,CCCCO,130.333333,4.666667,1.666667,55.000000,76.000000,9.333333,-9.600000,8.000000,0.000000,...,2.000000,13.000000,16.666667,10.800000,9.666667,-13.000000,-7.666667,-2.000000,-3.000000,0.333333

## Hallem and Carlson [k]

In [23]:
task_file = './fig1/k_Hallem_and_Carlson/data.csv'
df = pd.read_csv(task_file)
df.head()

,smiles,regression_Or2a,regression_Or7a,regression_Or9a,regression_Or10a,regression_Or19a,regression_Or22a,regression_Or23a,regression_Or33b,regression_Or35a,...,regression_Or59b,regression_Or65a,regression_Or67a,regression_Or67c,regression_Or82a,regression_Or85a,regression_Or85b,regression_Or85f,regression_Or88a,regression_Or98a
0,NCCCCN,-2,-53,23,-40,-38,8,-11,-29,-17,...,0,-20,-15,0,-20,-27,11,1,-32,5
1,NCCCCCN,-7,-58,18,-31,-34,9,-16,-32,-5,...,5,-19,-19,8,-18,-25,16,9,-26,9
2,O=C1CCCO1,1,17,50,-20,-36,39,-5,-18,64,...,14,-12,114,14,-23,-22,34,16,-24,17
3,CCC1CCC(=O)O1,7,-56,115,4,-31,136,3,0,154,...,16,0,36,34,-11,-17,40,47,-23,12
4,CCCCC1CCC(=O)O1,-1,-39,23,4,-27,37,-6,-15,19,...,-2,2,14,10,4,-27,161,24,-42,89

## Oliferenko et al. [n]

In [25]:
task_file = './fig1/n_Oliferenko_et_al/data.csv'
df = pd.read_csv(task_file)
df.head()

                        smiles  binary_classification_exp_med
0           CCCCCC(=O)N(C)CCCC                              1
1        CC(C)=CC(=O)N1CCCCCC1                              1
2          CCCCCC(=O)N(CC)CCCC                              0
3  CCCCN(CC)C(=O)/C=C/c1ccccc1                              0
4        C=CCN(CC=C)C(=O)CCCCC                              0

# Datasets for non olfaction related tasks

## Enteric GPCR binding (Kooistra_et_al) [p]

In [27]:
task_files = ['./fig1/p_Kooistra_et_al/5ht1a.csv',
              './fig1/p_Kooistra_et_al/cnr2.csv',
              './fig1/p_Kooistra_et_al/drd2.csv',
              './fig1/p_Kooistra_et_al/ghsr.csv',
              './fig1/p_Kooistra_et_al/oprk.csv',
             ]
receptor_idx = 0
df = pd.read_csv(task_files[receptor_idx])
df.head() # label for a particular GPCR

                                              smiles  regression_binding_score
0               C#CCOc1cccc2c1-c1cccc3c1C(C2)N(C)CC3                      7.30
1             C#CCOc1cccc2c1-c1cccc3c1C(C2)N(CCC)CC3                      7.26
2                 C#Cc1c[nH]c(CN2CCN(c3ccccc3)CC2)c1                      6.57
3         C(=Cc1ccccc1)CN1CCN(c2nc3ccsc3n3cccc23)CC1                      7.08
4  C1=C(c2c[nH]c3ccccc23)CC2CCC1N2CCOc1cccc2[nH]c...                      6.95

## Other molecular properties [l, m, o, q, r]

In [29]:
moleculenet_files = ['./fig1/lmoqr_other_molcule_properties/l_sider.csv', 
                     './fig1/lmoqr_other_molcule_properties/m_freesolv.csv',
                     './fig1/lmoqr_other_molcule_properties/o_esol.csv',
                     './fig1/lmoqr_other_molcule_properties/q_bace-1.csv', 
                     './fig1/lmoqr_other_molcule_properties/r_qm7.csv',]
task_idx = 0
df = pd.read_csv(moleculenet_files[task_idx])
df.head() # label(s) for a task

,smiles,binary_classification_Hepatobiliary disorders,binary_classification_Metabolism and nutrition disorders,binary_classification_Eye disorders,binary_classification_Investigations,binary_classification_Musculoskeletal and connective tissue disorders,binary_classification_Gastrointestinal disorders,binary_classification_Social circumstances,binary_classification_Immune system disorders,binary_classification_Reproductive system and breast disorders,...,"binary_classification_Congenital, familial and genetic disorders",binary_classification_Infections and infestations,"binary_classification_Respiratory, thoracic and mediastinal disorders",binary_classification_Psychiatric disorders,binary_classification_Renal and urinary disorders,"binary_classification_Pregnancy, puerperium and perinatal conditions",binary_classification_Ear and labyrinth disorders,binary_classification_Cardiac disorders,binary_classification_Nervous system disorders,"binary_classification_Injury, poisoning and procedural complications"
0,C1C2CNCC1C3=CC4=NC=CN=C4C=C23,1,1,1,1,1,1,1,1,1,...,0,1,1,1,1,0,1,1,1,1
1,CC(C)NCC(COC1=CC=C(C=C1)CCOC)O,1,1,1,1,1,1,1,1,1,...,0,1,1,1,0,0,1,1,1,1
2,C(=N)(N)N,0,1,0,1,0,1,0,0,0,...,0,1,1,1,1,0,0,1,1,0
3,CCOC1=NC2=CC=CC(=C2N1CC3=CC=C(C=C3)C4=CC=CC=C4...,0,0,0,1,1,1,0,0,0,...,0,0,1,0,1,0,0,0,1,0
4,C(C(=O)O)C(CC(=O)O)(C(=O)O)O,1,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,1

# Simulated dataset for extended data figure 3

## Wildman-Cripper LogP

In [41]:
task_file = './sfig3/logp/data.csv'
df = pd.read_csv(task_file)
df.head(5)

                                           smiles  regression_logP
0                             COC(OC)C(C)c1ccccc1           2.4090
1  CC(C)=CCCC(C)=CCOC(Cc1ccccc1)OCC=C(C)CCC=C(C)C           7.9738
2                         CCCCCCCCCCCCOS(=O)(=O)O           3.7267
3                              COc1ccc(C(C)=O)cc1           1.8978
4                                  CC(=O)c1ccccc1           1.8892

## ESOL

In [42]:
task_file = './sfig3/esol/data.csv'
df = pd.read_csv(task_file)
df.head(5)

                                           smiles  regression_ESOL
0                             COC(OC)C(C)c1ccccc1        -2.781643
1  CC(C)=CCCC(C)=CCOC(Cc1ccccc1)OCC=C(C)CCC=C(C)C        -8.335178
2                         CCCCCCCCCCCCOS(=O)(=O)O        -4.216423
3                              COc1ccc(C(C)=O)cc1        -2.247571
4                                  CC(=O)c1ccccc1        -2.078162

## QED

In [43]:
task_file = './sfig3/qed/data.csv'
df = pd.read_csv(task_file)
df.head(5)

                                           smiles  regression_QED
0                             COC(OC)C(C)c1ccccc1        0.662338
1  CC(C)=CCCC(C)=CCOC(Cc1ccccc1)OCC=C(C)CCC=C(C)C        0.228554
2                         CCCCCCCCCCCCOS(=O)(=O)O        0.431651
3                              COc1ccc(C(C)=O)cc1        0.601659
4                                  CC(=O)c1ccccc1        0.517047

## GPCR Binding (model-estimated)

In [45]:
task_files = ['./sfig3/gpcr_binding_model_estimated/5ht1a.csv',
              './sfig3/gpcr_binding_model_estimated/cnr2.csv',
              './sfig3/gpcr_binding_model_estimated/drd2.csv',
              './sfig3/gpcr_binding_model_estimated/ghsr.csv',
              './sfig3/gpcr_binding_model_estimated/oprk.csv',
             ]
receptor_idx = 0
df = pd.read_csv(task_files[receptor_idx])
df.head() # model estaimted label for a particular GPCR

                  smiles  regression_pred_pKd
0             CCOC(C)OCC             3.167474
1     CCCCCOC(C)OCCC(C)C             3.310190
2  COC(C)OC(C)OCc1ccccc1             5.185222
3           CCCCOC(C)OCC             3.423579
4      CCCCOC(C)OCCC(C)C             3.504179

# Metabolic Networks

In [31]:
task_file = './fig23_metabolic_network/data.csv'
df = pd.read_csv(task_file)
df.head(15) # csv contains the SMILES for different essential oil

,network_for_specie,from_compound_metacyc_id,to_compound_metacyc_id,from_compound_smiles,to_compound_smiles
0,ORG-5993,CPD-706,CPD-8134,C=C(CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@...,CC(C)[C@@H](C)CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3...
1,ORG-5993,CPD-8134,CPD-4161,CC(C)[C@@H](C)CC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3...,CC(C)[C@@H](C)/C=C/[C@@H](C)[C@H]1CC[C@H]2[C@@...
2,ORG-5993,CPD-4101,CPD-4124,C=C(CC[C@@H](C)[C@H]1CC[C@H]2C3=CC[C@H]4[C@H](...,C/C=C(/CC[C@@H](C)[C@H]1CC[C@H]2C3=CC[C@H]4[C@...
3,ORG-5993,EPOXYSQUALENE,CPD-13048,CC(C)=CCC/C(C)=C\CC/C(C)=C\CC/C=C(\C)CC/C=C(\C...,CC1(C)CC[C@]2(C)CC[C@]3(C)[C@H]4CC=C5[C@@H](CC...
4,ORG-5993,EPOXYSQUALENE,CPD-10307,CC(C)=CCC/C(C)=C\CC/C(C)=C\CC/C=C(\C)CC/C=C(\C...,CC(C)=CCC/C(C)=C\CC[C@@](C)(O)[C@@H]1CC[C@@H]2...
5,ORG-5993,EPOXYSQUALENE,CPD-90,CC(C)=CCC/C(C)=C\CC/C(C)=C\CC/C=C(\C)CC/C=C(\C...,C=C(C)[C@@H]1CC[C@]2(C)CC[C@]3(C)[C@H](CC[C@@H...
6,ORG-5993,CPD-7078,GDP-L-GALACTOSE,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...
7,ORG-5993,CPD-7078,CPD4FS-5,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,O=P([O-])([O-])O[C@H]1O[C@@H](CO)[C@@H](O)[C@H...
8,ORG-5993,GDP-L-GALACTOSE,GDP-MANNOSE,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...
9,ORG-5993,GDP-L-GALACTOSE,CPDQT-4,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,O=P([O-])([O-])O[C@H]1O[C@@H](CO)[C@@H](O)[C@@...
10,ORG-5993,GDP-L-GALACTOSE,GDP-D-GLUCOSE,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...
11,ORG-5993,GDP-MANNOSE,GDP-4-DEHYDRO-6-DEOXY-D-MANNOSE,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,C[C@H]1O[C@H](OP(=O)([O-])OP(=O)([O-])OC[C@H]2...
12,ORG-5993,MANNOSE-1P,GDP-MANNOSE,O=P([O-])([O-])O[C@H]1O[C@H](CO)[C@@H](O)[C@H]...,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...
13,ORG-5993,MANNOSE-1P,CPDQT-4,O=P([O-])([O-])O[C@H]1O[C@H](CO)[C@@H](O)[C@H]...,O=P([O-])([O-])O[C@H]1O[C@@H](CO)[C@@H](O)[C@@...
14,ORG-5993,GDP-D-GLUCOSE,GDP-MANNOSE,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nc1nc2c(ncn2[C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...

# Essential Oils

In [33]:
task_file = './fig4_essential_oil/data.csv'
df = pd.read_csv(task_file)
df.head(15) # csv contains the SMILES for different essential oil

            essential_oil                                  smiles
0     Abies alba cone oil                  CC(=C)[C@H]1CCC(=CC1)C
1     Abies alba cone oil                       CC1=CCC2CC1C2(C)C
2     Abies alba cone oil                     CC1(C)C2CCC(C2)C1=C
3     Abies alba cone oil                     CC1(C)C2CCC(=C)C1C2
4     Abies alba cone oil               CC(=O)OC1CC2CCC1(C)C2(C)C
5     Abies alba cone oil               CC1=CC[C@@H](CC1)C(C)(C)O
6     Abies alba cone oil  C\C1=C/CCC(=C)[C@H]2CC(C)(C)[C@@H]2CC1
7     Abies alba cone oil                   CC1(C)C2CCC1(C)C(O)C2
8     Abies alba cone oil                       CC(C)=CCCC(=C)C=C
9     Abies alba cone oil            CC1(C)CCCC2(C)C3CCC(C13)C2=C
10    Abies alba cone oil                      CC(C)=C1CCC(=CC1)C
11    Abies alba cone oil                     CC(C)=CCCC(C)(O)C=C
12    Abies alba cone oil                     CC1=CCC2C(C1)C2(C)C
13  Abies alba needle oil                  CC(=C)[C@H]1CCC(=CC1)C
14  Abies alba needle oil                       CC1=CCC2CC1C2(C)C

# Embeddings

In [37]:
all_emb_file = './embeddings/data.csv'
all_emb_df = pd.read_csv(all_emb_file)
all_emb_df.head()

,smiles,POM_dim0,POM_dim1,POM_dim2,POM_dim3,POM_dim4,POM_dim5,POM_dim6,POM_dim7,POM_dim8,...,POM_dim246,POM_dim247,POM_dim248,POM_dim249,POM_dim250,POM_dim251,POM_dim252,POM_dim253,POM_dim254,POM_dim255
0,CC/C=C\CC1C(=O)CCC1CC(=O)[O-],0.000000,1.288520,0.000000,0.000000,0.000000,3.270320,1.714564,0.530266,0.295287,...,0.000000,0.000000,0.000000,0.000000,0.000000,5.942628,0.000000,0.000000,0.000000,3.436328
1,C=C[C@]1(C)CC[C@@H]2C(=CC[C@H]3[C@@](C)(C=O)CC...,3.044895,0.000000,3.390288,6.324815,0.000000,2.213868,0.000000,0.000000,0.000000,...,4.073509,0.486997,0.000000,3.343546,0.000000,0.000000,1.708971,0.000000,3.365321,0.000000
2,CCCCCC/C=C/C=O,0.000000,0.000000,3.067747,0.000000,0.000000,2.591244,2.268885,0.221056,1.106228,...,2.293670,0.000000,0.839098,0.000000,0.000000,1.010614,0.000000,0.565965,0.000000,2.039558
3,CC1CCC(=O)C1=O,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.686685,2.118346,...,0.000000,2.726642,0.697944,0.042361,3.355646,2.324684,0.424983,1.637198,0.000000,2.907061
4,CCCC(=O)OC1C=CC2C3CCC(C3)C12,1.491022,1.703882,0.000000,0.000000,0.521094,1.581025,0.735047,0.498118,0.000000,...,0.708391,0.000000,0.000000,0.000000,0.000000,2.910626,0.000000,0.000000,0.726918,0.185117

# HParam and model perforamnces

In [40]:
hparam_perf_file = './fig1/best_hparam_and_performance.csv'
hparam_perf_df = pd.read_csv(hparam_perf_file)
hparam_perf_df

/Library/Python/3.8/site-packages/IPython/core/interactiveshell.py:3169: DtypeWarning: Columns (22,27,33,36,37,42,43,44,55) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,label,seed,r2,rmse,dataset,task_type,split_type,mol_emb_type,model_type,num_estimators,...,net_batchnorm_decay_rate,net_dropout,adam_init_lr,accuracy,auprc,auroc,f1,precision,recall,class_weight
0,overall,0,0.758275,0.059534,QED,REGRESSION,CROSS_VALIDATION,BFP,RF,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,overall,1,0.753172,0.059311,QED,REGRESSION,CROSS_VALIDATION,BFP,RF,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,overall,2,0.750360,0.059305,QED,REGRESSION,CROSS_VALIDATION,BFP,RF,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,overall,3,0.748112,0.060376,QED,REGRESSION,CROSS_VALIDATION,BFP,RF,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,overall,4,0.722332,0.062615,QED,REGRESSION,CROSS_VALIDATION,BFP,RF,512.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490223,target0,33,NaN,NaN,TROPIQ_FRAGRANCE,BINARY,LEAVE_ONE_MOLECULE_OUT,GRAPH,MPNN,NaN,...,0.95,0.25,0.001,0.631579,0.592138,0.747826,0.562500,0.529412,0.600000,NaN
490224,target0,34,NaN,NaN,TROPIQ_FRAGRANCE,BINARY,LEAVE_ONE_MOLECULE_OUT,GRAPH,MPNN,NaN,...,0.95,0.25,0.001,0.578947,0.664402,0.744928,0.428571,0.461538,0.400000,NaN
490225,target0,35,NaN,NaN,TROPIQ_FRAGRANCE,BINARY,LEAVE_ONE_MOLECULE_OUT,GRAPH,MPNN,NaN,...,0.95,0.25,0.001,0.578947,0.568201,0.750725,0.384615,0.454545,0.333333,NaN
490226,target0,36,NaN,NaN,TROPIQ_FRAGRANCE,BINARY,LEAVE_ONE_MOLECULE_OUT,GRAPH,MPNN,NaN,...,0.95,0.25,0.001,0.631579,0.744884,0.811594,0.500000,0.538462,0.466667,NaN
490227,target0,37,NaN,NaN,TROPIQ_FRAGRANCE,BINARY,LEAVE_ONE_MOLECULE_OUT,GRAPH,MPNN,NaN,...,0.95,0.25,0.001,0.631579,0.658627,0.727536,0.461538,0.545455,0.400000,NaN